title: default
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT

          fields:

            header.title:
              type: hidden
            content:
              type: hidden
            header.draft.issue.id:
              type: hidden
            header.draft.issue.summary:
              type: hidden
            header.draft.last_modified_by:
              type: hidden

            header.draft.title:
              type: text
              autofocus: true
              style: vertical
              label: PLUGIN_ADMIN.TITLE

            header.draft.content:
              type: editor
              validate:
                type: textarea

            header.media_order:
              type: pagemedia
              ordering@: header.draft.content
              label: PLUGIN_ADMIN.PAGE_MEDIA

        comparison:
          type: tab
          title: PLUGIN_TECART_REVIEW_WORKFLOW.COMPARISON
          fields:

            columns:
              type: columns
              fields:
                left:
                  type: column
                  fields:
                    yours_title:
                      type: spacer
                      title: Deine Änderungen:

                right:
                  type: column
                  fields:
                    remote_title:
                      type: spacer
                      title: Original:

            header.draft.content:
              readonly: true
              type: review
              label: PLUGIN_TECART_REVIEW_WORKFLOW.REVIEW
